language: node_js
node_js:
  - '0.10'
script:
  - 'npm test'
after_success:
  - 'npm run coveralls'

env:
  global:
    secure: vHab6EewdaQ5tuP30VAptt2QLSj54pxDqi/lSE14yS5a6ZPX6WXuOvx2ONU4NQyNKeUqdPLgZ8ZAEKa9DRbebE1eZWUdNpfa2x+pilhVRa3dB76kFL40iGBsbLw4YWm+a8VUAYDM6+jkR4mN1k6OAXnSoknBILtBhskr2aNgAN4=

deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: PzEeKM9pgZborGXH7qeIOoc3XDSSrZyPLxbDSyYi5qRvPWenQFjOQjxiVMU3owwvtO/82Kq1kqO6Kje0lEdhWVniVU42sD+lJuPvT9fVMHhauGCqaeRNAPHnQpuHge8ZgMKeOYlH6/LQPvZraaCmDTpkQwL+6+Hdd8lEgKwqUsQ=
